// <auto-generated />
namespace Faktury.Biz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _01012016 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_01012016));
        
        string IMigrationMetadata.Id
        {
            get { return "201512312323316_01012016"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
