// <auto-generated />
namespace Faktury.Biz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class City_and_Post : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(City_and_Post));
        
        string IMigrationMetadata.Id
        {
            get { return "201602132356582_City_and_Post"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
